$ANSIBLE_VAULT;1.1;AES256
64376535636161373037613064313932323835613931323939396464383236356162333534383664
3361323565313532333732373731646237633336383638620a303765363361616432643666383462
39343933636437646235613832363361366237343635616339316333643731613139383366613761
6231663664643665660a653766326237636233383635626639633131383663636539383236326663
36363662653333636365353632643237343533356635383264346530643436326562356135393235
34316234376361643630643137376438353863303162633266633762363234636265643239353561
37363234633662623334653834353662383933336539306634663331306365313639303431316130
36393131376666313163343032653433656331393031363931393333363031363436336232363238
3361
